const vscode = require("vscode");
const path = require("path");
const fs = require("fs");

// ── Compiled CSS (generated by `npm run build` from src/styles/panel.scss) ──
// Wrapped in a try so the extension still loads if the file is missing during
// development (e.g. before the first build).
let _compiledCss = '';
try {
  _compiledCss = require('./styles/compiled-css');
} catch {
  // eslint-disable-next-line no-console
  console.warn('[dev-agent] compiled-css.js not found — run `npm run build` to generate it');
}

// ── Panel HTML template (src/templates/panel.html) ────────────────────────
// Read once at startup; the template uses {{PLACEHOLDER}} syntax.
let _panelTemplate = '';
try {
  _panelTemplate = fs.readFileSync(path.join(__dirname, 'templates', 'panel.html'), 'utf8');
} catch {
  // eslint-disable-next-line no-console
  console.warn('[dev-agent] panel.html template not found');
}

// ─── Sidebar widget ────────────────────────────────────────────────────────

class DevAgentViewProvider {
  static viewType = "devAgent.mainView";

  constructor(context, onMessage) {
    this._context = context;
    this._onMessage = onMessage;
    this._view = null;
  }

  resolveWebviewView(webviewView) {
    this._view = webviewView;
    webviewView.webview.options = { enableScripts: true };
    webviewView.webview.html = this._buildSidebarHtml();
    webviewView.webview.onDidReceiveMessage(this._onMessage, null, this._context.subscriptions);
    webviewView.onDidDispose(() => { this._view = null; });
  }

  postMessage(msg) { this._view?.webview.postMessage(msg); }

  _buildSidebarHtml() {
    return `<!DOCTYPE html><html><head><meta charset="UTF-8"/><style>
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:var(--vscode-font-family);font-size:12px;
     color:var(--vscode-editor-foreground);
     background:var(--vscode-sideBar-background,var(--vscode-editor-background));
     height:100vh;display:flex;flex-direction:column;overflow:hidden}
.sb-top{padding:14px 14px 13px;border-bottom:1px solid var(--vscode-panel-border,rgba(128,128,128,.15))}
.sb-brand{display:flex;align-items:center;gap:7px;margin-bottom:11px}
.sb-mark{font-size:14px;line-height:1;opacity:.7;color:var(--vscode-focusBorder,#58a6ff)}
.sb-name{font-size:13px;font-weight:700;letter-spacing:-.3px}
.btn{
  background:var(--vscode-button-background);color:var(--vscode-button-foreground);
  border:none;border-radius:6px;padding:7px 12px;font:inherit;cursor:pointer;
  font-size:12px;width:100%;text-align:center;transition:opacity .12s;font-weight:500;
}
.btn:hover{opacity:.85}
.row{display:flex;align-items:center;gap:8px;padding:10px 14px 0}
.dot{width:7px;height:7px;border-radius:50%;background:var(--vscode-descriptionForeground);opacity:.2;flex-shrink:0;transition:all .3s}
.dot.on{background:#3fb950;opacity:1}
.dot.wait{background:#d29922;opacity:1;animation:p .9s infinite}
.dot.run{background:#58a6ff;opacity:1;animation:p .9s infinite}
.dot.done{background:#3fb950;opacity:1}
@keyframes p{0%,100%{opacity:1}50%{opacity:.2}}
.lbl{font-size:11px;color:var(--vscode-descriptionForeground);flex:1;
     white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.tool-lbl{
  font-size:10px;color:var(--vscode-descriptionForeground);opacity:.55;
  padding:3px 14px 0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;
  font-family:var(--vscode-editor-font-family,monospace);display:none;
}
hr{border:none;border-top:1px solid var(--vscode-panel-border,rgba(128,128,128,.12));margin:9px 0}
.kv{padding:5px 14px}
.k{font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.07em;
   color:var(--vscode-descriptionForeground);margin-bottom:3px;opacity:.7}
.v{font-size:11px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font-weight:500}
</style></head><body>
<div class="sb-top">
  <div class="sb-brand"><span class="sb-mark">◉</span><span class="sb-name">Dev Agent</span></div>
  <button class="btn" id="o">Open panel →</button>
</div>
<div class="row"><div class="dot" id="bd"></div><span class="lbl" id="bl">Offline</span></div>
<div class="row" style="padding-top:6px"><div class="dot" id="d"></div><span class="lbl" id="p">Idle</span></div>
<div class="tool-lbl" id="t"></div>
<hr/>
<div class="kv"><div class="k">Project</div><div class="v" id="pr">—</div></div>
<div class="kv"><div class="k">Provider</div><div class="v" id="pv">—</div></div>
<script>
const v=acquireVsCodeApi();
document.getElementById('o').onclick=()=>v.postMessage({type:'open_panel'});
const bd=document.getElementById('bd'),bl=document.getElementById('bl');
const d=document.getElementById('d'),p=document.getElementById('p'),t=document.getElementById('t');
window.addEventListener('message',e=>{
  const m=e.data;
  if(m.type==='bridge_ready'){
    bd.className='dot on'; bl.textContent='Ready · '+(m.providerLabel||'');
    document.getElementById('pv').textContent=m.providerLabel||'—';
  }
  if(m.type==='bridge_offline'){bd.className='dot';bl.textContent='Offline';}
  if(m.type==='bridge_starting'){bd.className='dot wait';bl.textContent='Starting…';}
  if(m.type==='phase_change'){d.className='dot run';p.textContent=m.phase||'Running';}
  if(m.type==='tool_call_start'&&m.tool){
    t.style.display='block';
    t.textContent='↳ '+(m.paramsSummary?m.paramsSummary.slice(0,42):m.tool);
  }
  if(m.type==='tool_call_end'){t.style.display='none';}
  if(m.type==='session_end'||m.type==='task_complete'){
    d.className='dot done';p.textContent='Done';t.style.display='none';
    setTimeout(()=>{d.className='dot';p.textContent='Idle';},5000);
  }
  if(m.type==='workspace_confirmed')document.getElementById('pr').textContent=m.name||'—';
});
</script></body></html>`;
  }
}

// ─── Main panel ────────────────────────────────────────────────────────────

class DevAgentPanel {
  static currentPanel = null;
  static initialState = { bridgeReady: false, bridgePort: 3333 };

  static revive(context, webviewPanel, onMessage) {
    DevAgentPanel.currentPanel = new DevAgentPanel(context, webviewPanel, onMessage);
    return DevAgentPanel.currentPanel;
  }

  static createOrReveal(context, onMessage) {
    if (DevAgentPanel.currentPanel) {
      DevAgentPanel.currentPanel._panel.reveal(vscode.ViewColumn.One);
      return { panel: DevAgentPanel.currentPanel, isNew: false };
    }
    const panel = vscode.window.createWebviewPanel(
      "devAgent.chat", "Dev Agent", vscode.ViewColumn.One,
      {
        enableScripts: true,
        retainContextWhenHidden: true,
        localResourceRoots: [vscode.Uri.joinPath(context.extensionUri, "dist")],
      },
    );
    DevAgentPanel.currentPanel = new DevAgentPanel(context, panel, onMessage);
    return { panel: DevAgentPanel.currentPanel, isNew: true };
  }

  constructor(context, panel, onMessage) {
    this._context = context;
    this._panel = panel;
    panel.webview.options = {
      enableScripts: true,
      localResourceRoots: [vscode.Uri.joinPath(context.extensionUri, "dist")],
    };
    panel.webview.html = this._buildHtml();
    panel.webview.onDidReceiveMessage((msg) => onMessage(msg, this), null, context.subscriptions);
    panel.onDidDispose(() => { DevAgentPanel.currentPanel = null; }, null, context.subscriptions);
  }

  postMessage(msg) { this._panel?.webview.postMessage(msg); }
  reveal() { this._panel?.reveal(vscode.ViewColumn.One); }

  _buildHtml() {
    const initJson = JSON.stringify(DevAgentPanel.initialState);
    const webview = this._panel.webview;
    const scriptUri = webview.asWebviewUri(
      vscode.Uri.joinPath(this._context.extensionUri, 'dist', 'panel-webview.js')
    );
    const csp = `default-src 'none'; style-src 'unsafe-inline'; script-src ${webview.cspSource}; img-src data: blob:; connect-src http://localhost:*;`;

    // If the template and compiled CSS are available, use them.
    if (_panelTemplate) {
      return _panelTemplate
        .replace('{{CSP}}', csp)
        .replace('{{INIT_DATA}}', initJson)
        .replace('{{COMPILED_CSS}}', _compiledCss)
        .replace('{{WEBVIEW_SCRIPT_URI}}', scriptUri.toString());
    }

    // Template missing — show a helpful error. This only happens when the
    // extension is loaded without running `npm run build` first.
    return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta http-equiv="Content-Security-Policy" content="${csp}">
<title>Dev Agent — Build Required</title>
<style>
body{font-family:sans-serif;display:flex;align-items:center;justify-content:center;
     height:100vh;margin:0;background:#1e1e1e;color:#d4d4d4;text-align:center}
.wrap{max-width:360px;padding:32px}
.icon{font-size:28px;margin-bottom:16px;opacity:.6}
h2{font-size:16px;font-weight:600;margin:0 0 10px}
p{font-size:13px;color:#888;line-height:1.6;margin:0 0 16px}
code{font-family:monospace;background:#2d2d2d;padding:3px 7px;border-radius:4px;
     color:#ce9178;font-size:12px;display:inline-block;margin-top:4px}
</style>
</head>
<body>
<div class="wrap">
  <div class="icon">◉</div>
  <h2>Dev Agent — Build required</h2>
  <p>The panel template and compiled CSS are missing. Run the build step to generate them:</p>
  <code>npm run build</code>
  <p style="margin-top:16px">Then reload the extension window (<kbd>Ctrl+R</kbd> / <kbd>Cmd+R</kbd>).</p>
</div>
</body>
</html>`;
  }
}

module.exports = { DevAgentViewProvider, DevAgentPanel };
